//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservationRoom
    {
        public int IdReservationRoom { get; set; }
        public int IdReservation { get; set; }
        public int IdRoom { get; set; }
    
        public virtual Reservation Reservation { get; set; }
        public virtual Room Room { get; set; }
    }
}
